-- ========================================================================
-- PRODUCTION POI MIGRATION - Complete Minnesota Outdoor Recreation Dataset
-- ========================================================================
-- Migration from Preview (138 POI) to Production (20 POI)
-- Target: Complete Minnesota parks, trails, and outdoor recreation areas
-- ========================================================================

-- Step 1: Clear existing POI data (backup first if needed)
TRUNCATE TABLE poi_locations CASCADE;

-- Step 2: Reset sequence for clean IDs
ALTER SEQUENCE poi_locations_id_seq RESTART WITH 1;

-- Step 3: Insert complete Minnesota POI dataset (138 locations)
INSERT INTO poi_locations (name, lat, lng, park_type, data_source, description, importance_rank) VALUES('Gooseberry Falls State Park', 47.1397, -91.469, 'State Park', 'manual', 'Spectacular waterfalls along Lake Superior with hiking trails', 10),
('Itasca State Park', 47.2181, -95.2058, 'State Park', 'manual', 'Headwaters of the Mississippi River with old-growth pines', 10),
('Split Rock Lighthouse State Park', 47.1999, -91.3895, 'State Park', 'manual', 'Iconic lighthouse on Lake Superior cliffs with hiking trails', 10),
('Taylors Falls State Park', 45.4005, -92.6518, 'State Park', 'manual', 'St. Croix River gorge with rock climbing and scenic overlooks', 10),
('Grand Portage National Monument', 47.9953, -89.6842, 'National Monument', 'seed_script', 'Historic fur trade depot and Ojibwe heritage', 12),
('Pipestone National Monument', 44.0133, -96.3253, 'National Monument', 'seed_script', 'Sacred Native American quarries', 12),
('Afton State Park', 44.8339, -92.7935, 'State Park', 'seed_script', 'Bluff-top views of the St. Croix River valley', 15),
('Bear Head Lake State Park', 47.8167, -92.05, 'State Park', 'seed_script', 'Wilderness escape with clear lakes and hiking trails', 15),
('Beaver Creek Valley State Park', 43.6381, -91.5972, 'State Park', 'seed_script', 'Spring-fed trout stream in a narrow valley', 15),
('Big Stone Lake State Park', 45.3667, -96.45, 'State Park', 'seed_script', 'Minnesota's western border lake with great fishing', 15),
('Blue Mounds State Park', 43.7067, -96.1892, 'State Park', 'seed_script', 'Sioux quartzite cliff and bison herd on the prairie', 15),
('Buffalo River State Park', 46.8667, -96.45, 'State Park', 'seed_script', 'Prairie river ecosystem', 15),
('Camden State Park', 44.3667, -95.9167, 'State Park', 'seed_script', 'Spring-fed Redwood River valley with swimming and trails', 15),
('Carley State Park', 44.1103, -92.1636, 'State Park', 'seed_script', 'Prairie restoration and Whitewater River access', 15),
('Cascade River State Park', 47.7089, -90.5, 'State Park', 'seed_script', 'Series of waterfalls flowing into Lake Superior', 15),
('Charles A. Lindbergh State Park', 45.9594, -94.3847, 'State Park', 'seed_script', 'Boyhood home of aviator Charles Lindbergh', 15),
('Crow Wing State Park', 46.2653, -94.3333, 'State Park', 'seed_script', 'Historic fur trading post at Mississippi River confluence', 15),
('Father Hennepin State Park', 46.1667, -93.45, 'State Park', 'seed_script', 'Peninsula park on Mille Lacs Lake with great fishing', 15),
('Flandrau State Park', 44.2889, -94.4592, 'State Park', 'seed_script', 'Swimming pond and trails along the Cottonwood River', 15),
('Forestville/Mystery Cave State Park', 43.6358, -92.2258, 'State Park', 'seed_script', 'Minnesota's longest cave and historic townsite', 15),
('Fort Ridgely State Park', 44.4433, -94.7267, 'State Park', 'seed_script', 'Historic fort site with golf course and trails', 15),
('Fort Snelling State Park', 44.8928, -93.1811, 'State Park', 'seed_script', 'Historic fort at confluence of Mississippi and Minnesota rivers', 15),
('Frontenac State Park', 44.5167, -92.35, 'State Park', 'seed_script', 'Bird migration hotspot overlooking Lake Pepin', 15),
('George H. Crosby Manitou State Park', 47.4833, -91.1167, 'State Park', 'seed_script', 'Backpacking paradise with rugged terrain and quiet solitude', 15),
('Glacial Lakes State Park', 45.55, -95.4, 'State Park', 'seed_script', 'Rolling hills and prairie lakes', 15),
('Glendalough State Park', 46.3333, -95.6833, 'State Park', 'seed_script', 'Heritage fishery and pristine lakes', 15),
('Gooseberry Falls State Park', 47.1389, -91.4706, 'State Park', 'seed_script', 'Famous for its spectacular waterfalls on the Gooseberry River', 15),
('Grand Portage State Park', 48, -89.5833, 'State Park', 'seed_script', 'Minnesota's highest waterfall and northernmost state park', 15),
('Great River Bluffs State Park', 43.9344, -91.4083, 'State Park', 'seed_script', 'Spectacular bluff-top views of the Mississippi River', 15),
('Hayes Lake State Park', 48.6333, -95.5167, 'State Park', 'seed_script', 'Remote northern wilderness park', 15),
('Hill Annex Mine State Park', 47.5167, -93.2667, 'State Park', 'seed_script', 'Historic open-pit iron mine with fossil hunting', 15),
('Interstate State Park', 45.3908, -92.6522, 'State Park', 'seed_script', 'Dramatic glacial potholes and cliffs along the St. Croix River', 15),
('Itasca State Park', 47.2419, -95.2061, 'State Park', 'seed_script', 'Headwaters of the Mississippi River and old-growth pine forests', 15),
('John A. Latsch State Park', 44.0667, -91.8667, 'State Park', 'seed_script', 'Blufftop park with Mississippi River valley views', 15),
('Judge C.R. Magney State Park', 47.8167, -90.05, 'State Park', 'seed_script', 'Home to the mysterious Devil's Kettle waterfall', 15),
('Kilen Woods State Park', 43.7333, -95.0667, 'State Park', 'seed_script', 'Oak woodlands along the Des Moines River', 15),
('Lac qui Parle State Park', 45, -95.8833, 'State Park', 'seed_script', 'Prairie wetlands and historic sites', 15),
('Lake Bemidji State Park', 47.5333, -94.8333, 'State Park', 'seed_script', 'Beautiful beaches and bog walk on Lake Bemidji', 15),
('Lake Bronson State Park', 48.7333, -96.6667, 'State Park', 'seed_script', 'Prairie meets aspen parkland', 15),
('Lake Carlos State Park', 45.9833, -95.35, 'State Park', 'seed_script', 'Clear water lake with great swimming', 15),
('Lake Louise State Park', 43.5414, -92.5006, 'State Park', 'seed_script', 'Prairie restoration with wildflowers and wildlife', 15),
('Lake Maria State Park', 45.3214, -93.9306, 'State Park', 'seed_script', 'Remnant of Big Woods with trails and backcountry campsites', 15),
('Lake Shetek State Park', 44.1044, -95.6917, 'State Park', 'seed_script', 'Largest lake in southwest Minnesota with diverse recreation', 15),
('Lake Vermilion State Park', 47.8292, -92.4283, 'State Park', 'seed_script', 'Newest state park on scenic Lake Vermilion', 15),
('McCarthy Beach State Park', 47.6522, -93.0603, 'State Park', 'seed_script', 'Sandy beach on Side Lake with excellent swimming', 15),
('Mille Lacs Kathio State Park', 46.1308, -93.7447, 'State Park', 'seed_script', 'Archaeological sites and hiking trails near Mille Lacs Lake', 15),
('Minneopa State Park', 44.1433, -94.0922, 'State Park', 'seed_script', 'Double waterfall and historic windmill', 15),
('Monson Lake State Park', 45.3167, -95.2667, 'State Park', 'seed_script', 'Historic site with swimming beach and hiking trails', 15),
('Myre-Big Island State Park', 43.6383, -93.3089, 'State Park', 'seed_script', 'Oak savanna on a glacial esker peninsula', 15),
('Nerstrand Big Woods State Park', 44.3453, -93.0972, 'State Park', 'seed_script', 'Last remnant of Big Woods with hidden waterfall', 15),
('Old Mill State Park', 48.25, -96.0833, 'State Park', 'seed_script', 'Historic mill and swimming hole', 15),
('Rice Lake State Park', 44.0833, -93.0667, 'State Park', 'seed_script', 'Southern hardwood forests', 15),
('Sakatah Lake State Park', 44.2333, -93.5167, 'State Park', 'seed_script', 'Hardwood forests and lake recreation', 15),
('Scenic State Park', 47.7089, -93.5833, 'State Park', 'seed_script', 'Virgin pine forests surrounding pristine lakes', 15),
('Sibley State Park', 45.0014, -95.0142, 'State Park', 'seed_script', 'Mount Tom offers panoramic views of the prairie landscape', 15),
('Soudan Underground Mine State Park', 47.8147, -92.2442, 'State Park', 'seed_script', 'Minnesota's oldest iron mine with underground tours', 15),
('Split Rock Creek State Park', 43.5, -96.3667, 'State Park', 'seed_script', 'Historic dam and lake on Split Rock Creek', 15),
('Split Rock Creek State Park', 43.8833, -96.3667, 'State Park', 'seed_script', 'Historic dam and recreation area', 15),
('Split Rock Lighthouse State Park', 47.2003, -91.3672, 'State Park', 'seed_script', 'Iconic lighthouse perched on a cliff overlooking Lake Superior', 15),
('Temperance River State Park', 47.5522, -90.8825, 'State Park', 'seed_script', 'Deep gorges and waterfalls carved by the Temperance River', 15),
('Tettegouche State Park', 47.3425, -91.1978, 'State Park', 'seed_script', 'Rugged coastline, inland lakes, and the Baptism River High Falls', 15),
('Upper Sioux Agency State Park', 44.7333, -95.4667, 'State Park', 'seed_script', 'Historic site with hiking and horseback riding trails', 15),
('Whitewater State Park', 44.0597, -92.0386, 'State Park', 'seed_script', 'Limestone bluffs and trout streams in the Driftless Area', 15),
('Wild River State Park', 45.5342, -92.7506, 'State Park', 'seed_script', '18 miles of St. Croix River shoreline with diverse habitats', 15),
('William O'Brien State Park', 45.2219, -92.7619, 'State Park', 'seed_script', 'Hardwood forests and wetlands along the St. Croix River', 15),
('Zippel Bay State Park', 48.8667, -94.85, 'State Park', 'seed_script', 'Lake of the Woods beaches and fishing', 15),
('Agassiz National Wildlife Refuge', 48.3, -96, 'Wildlife Refuge', 'seed_script', 'Vast wetlands in northwestern Minnesota', 18),
('Big Stone National Wildlife Refuge', 45.2667, -96.3333, 'Wildlife Refuge', 'seed_script', 'Prairie and wetland habitats', 18),
('Crane Meadows National Wildlife Refuge', 46.2333, -93.8333, 'Wildlife Refuge', 'seed_script', 'Wetlands for waterfowl and sandhill cranes', 18),
('Hamden Slough National Wildlife Refuge', 47.0167, -96.2833, 'Wildlife Refuge', 'seed_script', 'Prairie pothole wetlands and grasslands', 18),
('Minnesota Valley National Wildlife Refuge', 44.8075, -93.5272, 'Wildlife Refuge', 'seed_script', 'Urban refuge along the Minnesota River', 18),
('Northern Tallgrass Prairie National Wildlife Refuge', 44.0833, -96.1667, 'Wildlife Refuge', 'seed_script', 'Scattered prairie remnants preservation', 18),
('Rice Lake National Wildlife Refuge', 46.5167, -93.3333, 'Wildlife Refuge', 'seed_script', 'Wild rice lakes and diverse wildlife', 18),
('Rydell National Wildlife Refuge', 47.5333, -95.3, 'Wildlife Refuge', 'seed_script', 'Transition zone between prairie and forest', 18),
('Sherburne National Wildlife Refuge', 45.4167, -93.95, 'Wildlife Refuge', 'seed_script', 'Oak savanna and wetlands sanctuary', 18),
('Tamarac National Wildlife Refuge', 47.05, -95.6, 'Wildlife Refuge', 'seed_script', 'Lakes, bogs, and forests in the glacial lake country', 18),
('Baker Park Reserve', 45.0481, -93.5869, 'Regional Park', 'seed_script', 'Lake Independence shoreline with diverse habitats', 20),
('Battle Creek Regional Park', 44.9356, -93.0214, 'Regional Park', 'seed_script', 'Wooded valleys and ravines in St. Paul', 20),
('Bunker Hills Regional Park', 45.2181, -93.2839, 'Regional Park', 'seed_script', 'Wave pool, golf, and extensive trails', 20),
('Bunker Hills Regional Park', 45.245, -93.28, 'County Park', 'manual', 'Multi-use park with trails, beach, and recreational facilities', 20),
('Carver Park Reserve', 44.8783, -93.6283, 'Regional Park', 'seed_script', 'Largest park in Three Rivers system', 20),
('Chain of Lakes Regional Park', 44.9483, -93.3067, 'Regional Park', 'seed_script', 'Connected lakes with trails in Minneapolis', 20),
('Como Regional Park', 44.9819, -93.1494, 'Regional Park', 'seed_script', 'Historic park with zoo, conservatory, and lake', 20),
('Coon Rapids Dam Regional Park', 45.1444, -93.3117, 'Regional Park', 'seed_script', 'Mississippi River dam with visitor center', 20),
('Elm Creek Park Reserve', 45.1394, -93.4406, 'Regional Park', 'seed_script', 'Swimming pond, trails, and nature center', 20),
('Hyland Lake Park Reserve', 44.8433, -93.3717, 'Regional Park', 'seed_script', 'Year-round recreation with ski slopes and trails', 20),
('Lebanon Hills Regional Park', 44.7764, -93.1872, 'Regional Park', 'seed_script', '2,000 acres with mountain biking and hiking trails', 20),
('Minnehaha Falls Regional Park', 44.9153, -93.2111, 'County Park', 'manual', 'Historic waterfall park with paved trails and scenic overlooks', 20),
('Minnehaha Regional Park', 44.9153, -93.21, 'Regional Park', 'seed_script', '53-foot waterfall and limestone bluffs in Minneapolis', 20),
('Murphy-Hanrehan Park Reserve', 44.7394, -93.3439, 'Regional Park', 'seed_script', 'Glacial landscapes with challenging trails', 20),
('Rice Creek Chain of Lakes Park Reserve', 45.1389, -93.0917, 'Regional Park', 'seed_script', 'Multiple lakes connected by channels', 20),
('Rum River Central Regional Park', 45.36, -93.2, 'County Park', 'manual', 'River park with canoe access and hiking trails', 20),
('Saint Croix National Scenic Riverway', 45.4, -92.65, 'Scenic River', 'seed_script', 'Protected river corridor for paddling', 20),
('Theodore Wirth Regional Park', 44.9889, -93.3239, 'Regional Park', 'seed_script', 'Minneapolis' largest park with lakes and trails', 20),
('Chengwatana State Forest', 45.85, -92.8833, 'State Forest', 'seed_script', 'Pine forests with ATV and snowmobile trails', 22),
('D.A.R. State Forest', 45.9833, -93.1833, 'State Forest', 'seed_script', 'Hardwood forests near the St. Croix River', 22),
('Foot Hills State Forest', 46.85, -94.8333, 'State Forest', 'seed_script', 'Rolling hills and mixed forests', 22),
('General C.C. Andrews State Forest', 46.1667, -92.7, 'State Forest', 'seed_script', 'Historic forestry site with trails', 22),
('Kabetogama State Forest', 48.3333, -93, 'State Forest', 'seed_script', 'Gateway to Voyageurs National Park waters', 22),
('Lake of the Woods State Forest', 48.75, -95.0833, 'State Forest', 'seed_script', 'Vast northern waters and forests', 22),
('Nemadji State Forest', 46.5833, -92.5833, 'State Forest', 'seed_script', 'Red clay valleys and pine forests', 22),
('Paul Bunyan State Forest', 47.3667, -94.8833, 'State Forest', 'seed_script', 'Named for the legendary lumberjack', 22),
('Pillsbury State Forest', 46.6333, -94.2667, 'State Forest', 'seed_script', 'Diverse forest habitats with many lakes', 22),
('Sand Dunes State Forest', 46.4, -93.0667, 'State Forest', 'seed_script', 'Unique sand dune ecosystem with OHV recreation', 22),
('Savanna State Forest', 46.7833, -93.35, 'State Forest', 'seed_script', 'Jack pine forests and wetlands', 22),
('Snake River State Forest', 46.1333, -93.1167, 'State Forest', 'seed_script', 'Canoeing and camping along the Snake River', 22),
('Crosslake Recreation Area', 46.6581, -94.1133, 'Recreation Area', 'seed_script', 'Popular lake area in Brainerd Lakes region', 23),
('Gull Lake Recreation Area', 46.4167, -94.35, 'Recreation Area', 'seed_script', 'Large lake with multiple access points', 23),
('Lake Pahoja Recreation Area', 44.0833, -95.05, 'Recreation Area', 'seed_script', 'Small lake with camping and water activities', 23),
('Leech Lake Recreation Area', 47.0833, -94.3833, 'Recreation Area', 'seed_script', 'Minnesota's third largest lake', 23),
('Mississippi National River and Recreation Area', 44.9489, -93.0983, 'Recreation Area', 'seed_script', '72-mile river corridor through Twin Cities', 23),
('Pelican Lake Recreation Area', 46.6, -94.15, 'Recreation Area', 'seed_script', 'Excellent fishing and water sports', 23),
('Cannon Valley Trail', 44.4667, -92.9, 'Trail System', 'seed_script', '20 miles along the Cannon River', 24),
('Central Lakes State Trail', 46.2833, -95.05, 'Trail System', 'seed_script', '55 miles connecting lake communities', 24),
('Gateway State Trail', 45, -92.9333, 'Trail System', 'seed_script', '18 miles from St. Paul to Pine Point Park', 24),
('Glacial Lakes State Trail', 45.55, -95.1333, 'Trail System', 'seed_script', '22 miles through rolling prairie', 24),
('Heartland State Trail', 45.8, -94.75, 'Trail System', 'seed_script', '49 miles through lakes and forests', 24),
('Lake Wobegon Trail', 45.6167, -94.5833, 'Trail System', 'seed_script', '46 miles through Garrison Keillor country', 24),
('Minnesota River State Trail', 44.5333, -93.9667, 'Trail System', 'seed_script', 'Growing trail along Minnesota River valley', 24),
('Paul Bunyan State Trail', 46.35, -94.2, 'Trail System', 'seed_script', '120 miles - Minnesota's longest rail-trail', 24),
('Root River State Trail', 43.7833, -92.0667, 'Trail System', 'seed_script', '42 miles through bluff country', 24),
('Sakatah Singing Hills State Trail', 44.2167, -93.5333, 'Trail System', 'seed_script', '39 miles through lakes and towns', 24),
('Audubon Center of the North Woods', 46.8667, -93.1333, 'Nature Center', 'seed_script', 'Wildlife education and trails', 25),
('Deep Portage Conservation Reserve', 46.8333, -94.7167, 'Nature Center', 'seed_script', '6,000 acres of learning landscape', 25),
('Eagle Bluff Environmental Learning Center', 44.15, -92.0333, 'Nature Center', 'seed_script', 'Bluff-top learning center', 25),
('Long Lake Conservation Center', 46.8833, -93.5667, 'Nature Center', 'seed_script', 'Environmental education facility', 25),
('Wolf Ridge Environmental Learning Center', 47.4667, -91.3833, 'Nature Center', 'seed_script', 'Environmental education on Lake Superior', 25),
('Fort Snelling State Park', 44.8928, -93.1811, 'State Park', 'seed_script', 'Historic fort at confluence of Mississippi and Minnesota rivers', 15),
('Jeffers Petroglyphs', 44.0667, -95.05, 'Historic Site', 'seed_script', 'Ancient rock carvings on the prairie', 26),
('Lac qui Parle Mission', 45.0333, -95.9167, 'Historic Site', 'seed_script', '1835 mission site with trails', 26),
('Oliver H. Kelley Farm', 45.2333, -93.6667, 'Historic Site', 'seed_script', 'Historic farm with nature trails', 26),
('Crow River State Water Trail', 45.1333, -94.5, 'Water Trail', 'seed_script', 'Prairie river paddling', 27),
('Kettle River State Water Trail', 46.5167, -92.8667, 'Water Trail', 'seed_script', 'Whitewater paddling adventure', 27),
('Minnesota River State Water Trail', 44.8833, -93.9333, 'Water Trail', 'seed_script', 'Historic river route', 27),
('Red Lake River State Water Trail', 47.8833, -96.0833, 'Water Trail', 'seed_script', 'Northern river journey', 27),
('Straight River State Water Trail', 44.0167, -93.3, 'Water Trail', 'seed_script', 'Clear water paddling', 27),
('Whiteface River State Water Trail', 46.6667, -92.75, 'Water Trail', 'seed_script', 'Scenic paddling through forests', 27),
('Carlos Avery Wildlife Management Area', 45.28, -93.145, 'Wildlife Area', 'manual', 'Wildlife viewing and hunting area with hiking trails near Nowthen', 30);

-- Step 4: Verify POI count
SELECT COUNT(*) as total_poi FROM poi_locations;
