version: 2
updates:
  # Main package.json dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "rhspeer"
    commit-message:
      prefix: "deps"
      include: "scope"
    ignore:
      # Block React 19 until planned LTS upgrade
      - dependency-name: "react"
        versions: [">= 19.0.0"]
      - dependency-name: "react-dom"
        versions: [">= 19.0.0"]

  # Web app dependencies
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 5
    reviewers:
      - "rhspeer"
    commit-message:
      prefix: "deps(web)"
      include: "scope"
    ignore:
      # Block react-leaflet 5.x until React 19 upgrade
      - dependency-name: "react-leaflet"
        versions: ["5.x", ">= 5.0.0"]
      # Block major Vite versions until compatibility verified
      - dependency-name: "vite"
        versions: [">= 7.0.0"]
      # Block React 19 ecosystem until planned LTS upgrade
      - dependency-name: "react"
        versions: [">= 19.0.0"]
      - dependency-name: "react-dom"
        versions: [">= 19.0.0"]
      - dependency-name: "@types/react"
        versions: [">= 19.0.0"]
      - dependency-name: "@types/react-dom"
        versions: [">= 19.0.0"]

  # Test dependencies
  - package-ecosystem: "npm"
    directory: "/tests"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
    open-pull-requests-limit: 3
    reviewers:
      - "rhspeer"
    commit-message:
      prefix: "deps(tests)"
      include: "scope"

  # GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "12:00"
    open-pull-requests-limit: 3
    reviewers:
      - "rhspeer"
    commit-message:
      prefix: "ci"
      include: "scope"
