# Nearest Nice Weather - Simplified Development Environment
# Redis cache only - Database hosted on Neon cloud

version: '3.8'

services:
  # Redis for caching and session management (local only)
  redis:
    image: redis:${REDIS_VERSION:-7-alpine}
    container_name: ${PROJECT_NAME:-weather}_redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

# Persistent Data Storage
volumes:
  redis_data:
    driver: local

# Simple network
networks:
  default:
    driver: bridge