#!/bin/bash

# GitHub Token Setup - Secure Instructions
# =========================================
# This script provides secure setup instructions for GitHub authentication
# NEVER hardcode tokens in scripts or commit them to the repository!

echo "🔐 GitHub Token Setup Instructions"
echo "==================================="
echo ""
echo "⚠️  SECURITY NOTICE: The previous GitHub token has been revoked due to exposure."
echo ""
echo "To setup a new GitHub Personal Access Token securely:"
echo ""
echo "1. Create a new token at: https://github.com/settings/tokens"
echo "   - Click 'Generate new token (classic)'"
echo "   - Name: 'Nearest Nice Weather Development'"
echo "   - Expiration: Choose appropriate expiration"
echo "   - Scopes needed:"
echo "     ✓ repo (full control of private repositories)"
echo "     ✓ workflow (if using GitHub Actions)"
echo "     ✓ read:org (if accessing organization repos)"
echo ""
echo "2. Store the token securely in .env file (already in .gitignore):"
echo "   echo 'GITHUB_PERSONAL_ACCESS_TOKEN=your_token_here' >> .env"
echo ""
echo "3. For GitHub CLI authentication (recommended):"
echo "   gh auth login"
echo "   - Choose GitHub.com"
echo "   - Choose HTTPS"
echo "   - Authenticate with a web browser or paste token"
echo ""
echo "4. For MCP servers, add to your shell profile (~/.bashrc or ~/.zshrc):"
echo "   export GITHUB_TOKEN=\"\$(gh auth token 2>/dev/null)\""
echo ""
echo "5. For wiki operations requiring authentication:"
echo "   git config --global credential.helper store"
echo "   - Use username and token when prompted (not password)"
echo ""
echo "Current GitHub CLI status:"
gh auth status 2>&1 || echo "   GitHub CLI not authenticated. Run 'gh auth login'"
echo ""
echo "⚠️  IMPORTANT SECURITY PRACTICES:"
echo "   • NEVER hardcode tokens in scripts"
echo "   • NEVER commit tokens to git (check .gitignore)"
echo "   • Use environment variables or GitHub CLI for authentication"
echo "   • Rotate tokens regularly"
echo "   • Use minimal required scopes"
echo ""
echo "📝 Files to check/update after token setup:"
echo "   • .env (for local environment variables)"
echo "   • .mcp/claude-desktop-config.json (for MCP server auth)"
echo "   • Vercel environment variables (for production)"