name: Capability
description: A strategic capability that delivers significant business value and may span multiple epics
title: "[Capability] "
labels: ["type:capability"]
body:
  - type: markdown
    attributes:
      value: |
        ## Capability Template
        
        Use this template for major strategic capabilities that represent significant business value and may include multiple epics.
        
  - type: textarea
    id: capability-description
    attributes:
      label: Capability Description
      description: Strategic description of the capability and its role in the business
      placeholder: "Describe the strategic capability and how it advances business objectives"
    validations:
      required: true
      
  - type: textarea
    id: strategic-value
    attributes:
      label: Strategic Business Value
      description: What strategic business outcomes does this capability enable?
      placeholder: "This capability enables the business to... which supports our strategic goal of..."
    validations:
      required: true
      
  - type: textarea
    id: revenue-impact
    attributes:
      label: Revenue Impact
      description: Expected revenue impact and timeline
      placeholder: |
        - Immediate impact: $X in Year 1
        - Long-term impact: $X in Years 2-3
        - Revenue model: How this generates revenue
    validations:
      required: true
      
  - type: dropdown
    id: size
    attributes:
      label: Capability Size
      description: Strategic size estimate
      options:
        - XL (1-2 quarters)
        - XXL (2-4 quarters)
        - MEGA (4+ quarters)
    validations:
      required: true
      
  - type: textarea
    id: epics
    attributes:
      label: Component Epics
      description: Major epics that comprise this capability
      placeholder: |
        - [ ] Epic 1: Brief description
        - [ ] Epic 2: Brief description
        - [ ] Epic 3: Brief description
        
        Note: Epic breakdown may evolve during planning
      
  - type: textarea
    id: market-opportunity
    attributes:
      label: Market Opportunity
      description: Market size, competition, and opportunity analysis
      placeholder: "Market size, competitive landscape, and why now is the right time for this capability"
      
  - type: textarea
    id: success-metrics
    attributes:
      label: Strategic Success Metrics
      description: Key performance indicators for capability success
      placeholder: |
        - KPI 1: Baseline → Target (Timeline)
        - KPI 2: Baseline → Target (Timeline)
        - KPI 3: Baseline → Target (Timeline)
        
  - type: textarea
    id: risks-and-assumptions
    attributes:
      label: Strategic Risks & Assumptions
      description: Major risks and key assumptions at the capability level
      placeholder: |
        **Key Assumptions:**
        - Assumption 1
        - Assumption 2
        
        **Major Risks:**
        - Risk 1: Impact → Mitigation
        - Risk 2: Impact → Mitigation
        
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Capability Acceptance Criteria
      description: Strategic criteria for capability completion
      placeholder: |
        - [ ] All component epics delivered
        - [ ] Strategic success metrics achieved
        - [ ] Market validation completed
        - [ ] Revenue targets met or exceeded
        - [ ] Capability operationally sustainable