name: Epic
description: A large body of work that can be broken down into multiple user stories
title: "[Epic] "
labels: ["type:epic"]
body:
  - type: markdown
    attributes:
      value: |
        ## Epic Template
        
        Use this template for large features or initiatives that span multiple sprints and can be broken down into smaller user stories.
        
  - type: textarea
    id: epic-description
    attributes:
      label: Epic Description
      description: High-level description of the epic and its business value
      placeholder: "Describe the overall goal and business value of this epic"
    validations:
      required: true
      
  - type: textarea
    id: business-value
    attributes:
      label: Business Value
      description: What business problem does this solve? What value does it provide?
      placeholder: "This epic enables users to... which results in increased engagement/revenue/retention"
    validations:
      required: true
      
  - type: textarea
    id: success-metrics
    attributes:
      label: Success Metrics
      description: How will we measure the success of this epic?
      placeholder: |
        - Metric 1: Target value
        - Metric 2: Target value
        - Metric 3: Target value
    validations:
      required: true
      
  - type: dropdown
    id: size
    attributes:
      label: Epic Size
      description: Relative size estimate
      options:
        - L (1-2 sprints)
        - XL (2-4 sprints)
        - XXL (4+ sprints)
    validations:
      required: true
      
  - type: textarea
    id: user-stories
    attributes:
      label: User Stories (Initial List)
      description: List of potential user stories that make up this epic
      placeholder: |
        - [ ] Story 1: Brief description
        - [ ] Story 2: Brief description
        - [ ] Story 3: Brief description
        
        Note: This list may evolve as the epic is refined
      
  - type: textarea
    id: assumptions
    attributes:
      label: Assumptions & Dependencies
      description: Key assumptions and external dependencies
      placeholder: "List any assumptions about user behavior, technical constraints, or external dependencies"
      
  - type: textarea
    id: risks
    attributes:
      label: Risks & Mitigation
      description: Potential risks and how we'll address them
      placeholder: |
        - Risk 1: Description → Mitigation strategy
        - Risk 2: Description → Mitigation strategy
        
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Epic Acceptance Criteria
      description: High-level criteria for epic completion
      placeholder: |
        - [ ] All user stories completed and deployed
        - [ ] Success metrics achieved
        - [ ] User acceptance testing completed
        - [ ] Performance requirements met