name: Story
description: 👤 User-focused work item (3-13 story points)
title: "Story: "
labels: ["type: story"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 👤 User Story Template
        Create a user-focused work item as part of an Epic. Stories represent functionality from the user's perspective.

  - type: dropdown
    id: sprint
    attributes:
      label: Sprint Assignment
      description: Which sprint iteration is this story assigned to?
      options:
        - Database + Weather API (Current)
        - Revenue + Launch (Next)
        - Post-MVP (Future)
    validations:
      required: true

  - type: dropdown
    id: size
    attributes:
      label: Story Size
      description: Estimated effort using standard story point sizing
      options:
        - XS (1-2 points)
        - S (3-5 points) 
        - M (8-13 points)
        - L (20-21 points)
        - XL (34+ points)
    validations:
      required: true

  - type: input
    id: parent_epic
    attributes:
      label: Parent Epic
      description: Link to the parent Epic issue (e.g., #123)
      placeholder: "#123"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: Priority level for this story
      options:
        - Critical
        - High
        - Medium
        - Low
      default: 2
    validations:
      required: true

  - type: checkboxes
    id: technical_labels
    attributes:
      label: Technical Areas
      description: Select all technical areas this story involves
      options:
        - label: Database (schema, queries, migrations)
        - label: Weather API (service integration)
        - label: Frontend (UI/UX, React components)
        - label: Backend (server-side logic, APIs)
        - label: Mobile (optimization, responsive design)
        - label: Analytics (tracking, metrics, reporting)
        - label: Revenue (monetization, ads, payments)

  - type: textarea
    id: user_story
    attributes:
      label: User Story
      description: Write the story from the user's perspective
      placeholder: "As a [type of user], I want [goal/desire] so that [benefit/value]."
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: List specific, testable criteria for story completion
      placeholder: |
        - [ ] Given [context], when [action], then [outcome]
        - [ ] Given [context], when [action], then [outcome]  
        - [ ] Given [context], when [action], then [outcome]
    validations:
      required: true

  - type: textarea
    id: implementation_details
    attributes:
      label: Implementation Details
      description: Technical requirements and file references
      placeholder: |
        **File References:**
        - Primary file: [file path]
        - Function/component: [specific location in file]
        - Dependencies: [other files that need changes]

        **Technical Requirements:**
        - [ ] Requirement 1
        - [ ] Requirement 2
        - [ ] Requirement 3

  - type: textarea
    id: definition_of_done
    attributes:
      label: Definition of Done  
      description: Checklist for story completion
      value: |
        - [ ] Code implemented and tested
        - [ ] User acceptance criteria met
        - [ ] Code reviewed and approved
        - [ ] Documentation updated if needed
        - [ ] Sub-issues completed (if any)

  - type: checkboxes
    id: workflow_labels
    attributes:
      label: Workflow Status (optional)
      description: Add workflow labels if applicable
      options:
        - label: blocked (waiting on external dependency)
        - label: urgent (high priority, expedite work)
        - label: needs-review (ready for validation/testing)