name: User Story
description: A user story representing a specific feature or functionality requirement
title: "[Story] "
labels: ["type:story"]
body:
  - type: markdown
    attributes:
      value: |
        ## User Story Template

        Use this template for individual features or functionality requirements that can be completed in a sprint.

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: As a [user type], I want [functionality] so that [benefit]
      placeholder: "As a Minnesota outdoor enthusiast, I want to see weather conditions on a map so that I can find the best locations for my activities."
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Define what "done" means for this story
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: dropdown
    id: size
    attributes:
      label: Story Size
      description: Relative size estimate
      options:
        - XS (1-2 hours)
        - S (2-4 hours)
        - M (4-8 hours)
        - L (1-2 days)
        - XL (2-3 days)
    validations:
      required: true

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Notes
      description: Implementation details, dependencies, or constraints
      placeholder: "Any technical considerations, API dependencies, or architectural notes"

  - type: checkboxes
    id: dependencies
    attributes:
      label: Dependencies
      description: Check all that apply for this story
      options:
        - label: Requires backend API changes
        - label: Requires database schema updates
        - label: Requires frontend UI changes
        - label: Requires third-party integration
        - label: No external dependencies

  - type: dropdown
    id: blocked-reason
    attributes:
      label: Blocked Reason (if applicable)
      description: Select if this story is currently blocked
      options:
        - Not blocked
        - Waiting for API endpoint
        - Waiting for design approval
        - Waiting for external dependency
        - Waiting for technical decision
        - Waiting for business requirements
        - Waiting for testing environment

  - type: textarea
    id: definition-of-done
    attributes:
      label: Definition of Done
      description: Checklist for completion
      value: |
        - [ ] Code implemented and tested
        - [ ] Unit tests written and passing
        - [ ] Integration tests passing
        - [ ] Code reviewed and approved
        - [ ] Documentation updated
        - [ ] Deployed to preview environment
        - [ ] Acceptance criteria verified
