# Comprehensive CI/CD Pipeline
# Nearest Nice Weather - Weather Intelligence Platform
# Consolidated: Security + Quality + Deployment for team development

name: 'Comprehensive CI/CD'

on:
  push:
    branches: [ main, develop, preview, feature/* ]
  pull_request:
    branches: [ main, develop, preview ]
  workflow_dispatch: # Allow manual triggers

# Environment variables
env:
  NODE_VERSION: '20'  # LTS version for team consistency

jobs:
  # Stage 1: Security & Quality Gates - Fast feedback for developers
  security-and-quality:
    name: 'Security & Quality Gates'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v5
      with:
        fetch-depth: 0 # Full history for security scanning

    - name: 'Setup Node.js'
      uses: actions/setup-node@v5
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: 'Install Dependencies'
      run: npm ci

    # Security: Secret scanning with TruffleHog OSS
    - name: 'TruffleHog Secret Scanning'
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: ${{ github.event.before != '0000000000000000000000000000000000000000' && github.event.before || 'HEAD~1' }}
        head: HEAD
        extra_args: --debug --only-verified
      continue-on-error: true

    # Quality: Linting
    - name: 'Lint Check'
      run: |
        cd apps/web && npm run lint

    # Quality: Type checking
    - name: 'Type Check'
      run: |
        cd apps/web && npm run type-check

    # Security: Dependency audit
    - name: 'Security Audit'
      run: |
        npm audit --audit-level moderate || true
        echo "Security audit completed (non-blocking for development)"

    # Quality: Build test
    - name: 'Build Validation'
      run: |
        cd apps/web && npm run build

  # Stage 2: Advanced Security Analysis (parallel with quality gates)
  advanced-security:
    name: 'Advanced Security Analysis'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      security-events: write
    if: github.event_name == 'push' || github.event_name == 'pull_request'

    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v5

    - name: 'Setup Node.js'
      uses: actions/setup-node@v5
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: 'Install Dependencies'
      run: npm ci

    # Security: CodeQL analysis
    - name: 'Initialize CodeQL'
      uses: github/codeql-action/init@v3
      with:
        languages: javascript,typescript
      continue-on-error: true

    - name: 'Build for CodeQL Analysis'
      run: |
        cd apps/web && npm run build || true  # Allow build failures for security scanning

    - name: 'Perform CodeQL Analysis'
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:javascript"
      continue-on-error: true

  # Stage 3: Integration Tests (when implemented)
  integration-tests:
    name: 'Integration Tests'
    runs-on: ubuntu-latest
    needs: [security-and-quality]
    timeout-minutes: 10
    if: false  # Disabled until test suite is implemented

    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v5

    - name: 'Setup Node.js'
      uses: actions/setup-node@v5
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: 'Install Dependencies'
      run: npm ci

    - name: 'Run Tests'
      run: |
        cd apps/web && npm run test

  # Stage 4: Preview Deployment (for team validation)
  deploy-preview:
    name: 'Deploy Preview'
    runs-on: ubuntu-latest
    needs: [security-and-quality]
    if: github.event_name == 'pull_request'
    timeout-minutes: 10

    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v5

    - name: 'Setup Node.js'
      uses: actions/setup-node@v5
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: 'Install Vercel CLI'
      run: npm install --global vercel@latest

    - name: 'Deploy to Preview'
      env:
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |
        cd apps/web
        vercel --token=$VERCEL_TOKEN --yes
      continue-on-error: true

    - name: 'Comment Preview URL'
      uses: actions/github-script@v8
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🚀 Preview deployment ready! Check the deployment logs for the URL.'
          });
      continue-on-error: true

  # Stage 5: Production Deployment (protected)
  deploy-production:
    name: 'Deploy Production'
    runs-on: ubuntu-latest
    needs: [security-and-quality, advanced-security]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    timeout-minutes: 15
    environment: production  # Requires approval for production deployments

    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v5

    - name: 'Setup Node.js'
      uses: actions/setup-node@v5
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: 'Install Dependencies'
      run: npm ci

    # Security: Generate SBOM (Software Bill of Materials)
    - name: 'Generate SBOM'
      run: |
        npm install -g @cyclonedx/cyclonedx-npm
        cd apps/web
        cyclonedx-npm --output-file ../../sbom.json
      continue-on-error: true

    - name: 'Upload SBOM Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: software-bill-of-materials
        path: sbom.json
        retention-days: 30
      if: always()

    - name: 'Install Vercel CLI'
      run: npm install --global vercel@latest

    - name: 'Deploy to Production'
      env:
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |
        cd apps/web
        vercel --prod --token=$VERCEL_TOKEN --yes

    - name: 'Deployment Success Notification'
      uses: actions/github-script@v8
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: '🚀 Production Deployment Complete',
            body: `Production deployment completed successfully!\n\nCommit: ${context.sha}\nWorkflow: ${context.workflow}\nRun: ${context.runNumber}`
          });
      continue-on-error: true

  # Stage 6: Post-Deployment Validation
  post-deployment:
    name: 'Post-Deployment Validation'
    runs-on: ubuntu-latest
    needs: [deploy-production]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    timeout-minutes: 5

    steps:
    - name: 'Validate Deployment'
      run: |
        echo "✅ Security scanning completed"
        echo "✅ Quality gates passed"
        echo "✅ Production deployment successful"
        echo "🎉 Pipeline completed successfully"
